### ISSUE TITLE
最新源码编译出来，运行一会就会提示未运行

### ISSUE THREAD

**Issue by ssdsl0126** [iwrt/luci-app-ikoolproxy#70]
如题

**Comment by project-lede** [comment]
重启下

**Comment by ssdsl0126** [comment]
> 重启下

尝试过了，不行，是使用lede源码进行编译的

**Comment by alexliu269** [comment]
拉取这个git clone https://github.com/godros/luci-app-godproxy.git编译后一切正常。使用这个https://github.com/project-lede/luci-app-godproxy.git编译就出现问题。不知道什么原因。你可以试一下

**Comment by iwrt** [comment]
估计是你编译问题。第一个地址都不存在。我编译的都没有问题。一直运行。你看看自己的依赖都没有搞对。
