### ISSUE TITLE
op安装新版的2个ipk没界面显示？

### ISSUE THREAD

**Issue by kennylee60** [iwrt/luci-app-ikoolproxy#71]
如题，是缺了什么吗？

**Comment by iwrt** [comment]
最好是编译安装。安装ipk需要先安装依赖。

**Comment by kennylee60** [comment]
> 最好是编译安装。安装ipk需要先安装依赖。

Package openssl-util (1.1.1l-1) installed in root is up to date.
Package ipset (7.6-1) installed in root is up to date.
Package dnsmasq-full (2.86-1) installed in root is up to date.
Unknown package 'diffutils'.
Unknown package 'iptables-mod-nat-extra'.
Not downgrading package uclient-fetch on root from 2021-05-14-6a6011df-1 to 1.21.1-3.
Package ca-bundle (20210119-1) installed in root is up to date.
Package ca-certificates (20210119-1) installed in root is up to date.
Package libustream-openssl20201210 (2020-12-10-68d09243-2) installed in root is up to date.
Collected errors:
 * opkg_conf_parse_file: /etc/opkg/customfeeds.conf:4: Ignoring invalid line: `src-git opentopd  https://github.com/sirpdboy/sirpdboy-package'
 * opkg_conf_parse_file: /etc/opkg/customfeeds.conf:5: Ignoring invalid line: `git clone https://github.com/siropboy/sirpdboy-package package/sirpdboy-package'
 * opkg_install_cmd: Cannot install package diffutils.
 * opkg_install_cmd: Cannot install package iptables-mod-nat-extra.

手动运行依赖提示这个
