### ISSUE TITLE
最新版本两个ipk装了没有设置见面

### ISSUE THREAD

**Issue by spirytuslove** [iwrt/luci-app-ikoolproxy#72]
大佬我看有人问过是缺少依赖 问题是自己怎么编译啊  不会编译要怎么安装依赖包然后能出来界面啊。。。

**Comment by kennylee60** [comment]
我也是这样，不知道怎么解决

**Comment by gbeta** [comment]
是的，没有

**Comment by spirytuslove** [comment]
那你们怎么解决的啊

**Comment by iwrt** [comment]
用这个固件，自带ikoolproxy   http://pan.i-wrt.com/x64/1907/

**Comment by kennylee60** [comment]
> 用这个固件，自带ikoolproxy http://pan.i-wrt.com/x64/1907/

这个要登录吗，找不到下载的地方

**Comment by iwrt** [comment]
不要登录，直接下   https://pan.i-wrt.com/X64/1907/

**Comment by iwrt** [comment]
和以前的KPR以及KPR Plus还有+，都不兼容。意思是你要么彻底删除以前的，要么重刷一个没有KoolProxy的固件，再新安装ikoolproxy。

**Comment by spirytuslove** [comment]
彻底删除要删除哪些啊  我想彻底删除godproxy然后重新装这个  冲刷固件太折腾了

**Comment by gbeta** [comment]
重启解决

**Comment by spirytuslove** [comment]
确实  原来差一步重启  重启可以了😅
