### ISSUE TITLE
电视盒子上的爱奇艺打不开

### ISSUE THREAD

**Issue by kennysino** [iwrt/luci-app-ikoolproxy#74]
我在openwrt路由器上安装了这个
就是按默认的设置
电视盒子上的腾讯视频没有广告了
但是爱奇艺其实也经常使用的
电视盒子上的爱奇艺“银河奇异果”却显示网络不通
把iKoolProxy关闭就能正常播放了（当然是有广告的）
请问这个要怎么处理呢
感谢

**Comment by kennysino** [comment]
芒果tv也不能打开
是要怎么设置吗

**Comment by iwrt** [comment]
情况不一样，我家里默认配置，爱奇艺能打开，也没有广告。按你情况看，是不是过滤模式是https。

**Comment by iwrt** [comment]
默认规则只要视频规则试试
