### ISSUE TITLE
upload error for support more rules,thank you!

### ISSUE THREAD

**Issue by jkle112** [iwrt/luci-app-ikoolproxy#75]
OpenWrt X64
Thu Dec  9 10:15:18 2021 daemon.info koolproxy[20864]: koolproxy v3.8.5
Thu Dec  9 10:15:19 2021 daemon.err qemu-ga[20889]: 1639016119.340656: critical: error opening channel: No such file or directory
Thu Dec  9 10:15:19 2021 daemon.err qemu-ga[20889]: 1639016119.340662: critical: error opening channel
Thu Dec  9 10:15:19 2021 daemon.err qemu-ga[20889]: 1639016119.340665: critical: failed to create guest agent channel
Thu Dec  9 10:15:19 2021 daemon.err qemu-ga[20889]: 1639016119.340669: critical: failed to initialize guest agent channel
Thu Dec  9 10:15:19 2021 daemon.info procd: Instance qemu-ga::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Thu Dec  9 10:15:19 2021 daemon.info procd: Instance snort::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: WARN: line=75073, support rule like "http://$domain=", but advise to use a better one instead
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: WARN: line=75074, support rule like "http://$domain=", but advise to use a better one instead
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: WARN: line=75075, support rule like "http://$domain=", but advise to use a better one instead
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: WARN: line=75076, support rule like "http://$domain=", but advise to use a better one instead
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: WARN: line=75077, support rule like "http://$domain=", but advise to use a better one instead
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule regex compile error line_no:78192 90 90 text=[^\w\d_\-.%]?http\(\?:s\|)://m\\\.\[[^\w\d_\-.%]?/\].*/\\d\{3,\}\\\.htm\[lm\]\\\?\\d\{0,\} offset:25
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=79333 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=79339 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=79445 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule replace parse error, line=79554
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=79668 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=79749 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=79966 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=80380 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=80653 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=80716 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=80736 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=81026 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=81158 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=81179 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=81197 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=81920 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=83355 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=83397 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=83742 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=84390 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=84539 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=85277 not support '$f@'
Thu Dec  9 10:15:19 2021 daemon.err koolproxy[20864]: rule line=86451 not support '$f@'
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501845 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501846 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501847 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501848 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501849 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501850 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501851 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501852 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501853 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501854 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501855 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501856 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501857 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501858 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501859 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501860 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501861 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501862 not support ','
Thu Dec  9 10:15:23 2021 daemon.err koolproxy[20864]: rule line=501863 not support ','

**Comment by iwrt** [comment]
你这是哪里的规则

**Comment by jkle112** [comment]
自己添加了一些规则，保证IKOOLPROXY可以正常运行，不知道是哪些包含的问题，发一下，如果支持更好！
chrome 浏览器扩展adguard，ublock  origin,adblock plus 等的规则不知道是否有机会支持。

**Comment by iwrt** [comment]
自带的规则足够用了

**Comment by jkle112** [comment]
之所以选择你的，是因为它可以过滤网页，我升级规则后，防护能力增强，具体不能说，但是确实很好用，只是美中不足，例如adblock plus 的easylist+chinalist，实在不行我就只能用adguardhome了，打扰了！

**Comment by iwrt** [comment]
最早是abp的还有fanboy，经过提取后还没有现在的规则好用。yhosts规则试试。

**Comment by iwrt** [comment]
你把https证书一装。一片干净

**Comment by jkle112** [comment]
默认是不装HTTPS的，因为麻烦，此外有的设备装不了，
默认配置就很好了，我添加规则是要增强安全性能，所以希望支持一些常用的规则。
