### ISSUE TITLE
打开ikoolproxy导致Emby远程访问地址不对

### ISSUE THREAD

**Issue by kingjoydom** [iwrt/luci-app-ikoolproxy#79]
openwrt主路由打开ikoolproxy后Emby远程访问的地址变成另外一个地址；
如何设置局域网只有某个IP过滤广告？

**Comment by alexliu269** [comment]
加入超级白名单可以尝试一下，可能是过滤处于最高优先级，当需要转发的时候，没有转发到正确的位置和端口。我的端口转发开启这个也不能正常转发。还有一个，在防火墙里你可以试试添加这个，
iptables -t nat -A PREROUTING -p udp --dport 你Emby使用的端口 -j REDIRECT --to-ports 你Emby使用的端口
iptables -t nat -A PREROUTING -p tcp --dport 你Emby使用的端口 -j REDIRECT --to-ports 你Emby使用的端口
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p udp --dport 你Emby使用的端口 -j REDIRECT --to-ports 你Emby使用的端口
[ -n "$(command -v ip6tables)" ] && ip6tables -t nat -A PREROUTING -p tcp --dport 你Emby使用的端口 -j REDIRECT --to-ports 你Emby使用的端口

**Comment by alexliu269** [comment]
加入超级白名单可以尝试一下，可能是过滤处于最高优先级，当需要转发的时候，没有转发到正确的位置和端口。我的端口转发开启这个也不能正常转发。还有一个，在防火墙里你可以试试添加这个，
iptables -t nat -A PREROUTING -p udp --dport 你Emby使用的端口 -j REDIRECT --to-ports 你Emby使用的端口
iptables -t nat -A PREROUTING -p tcp --dport 你Emby使用的端口 -j REDIRECT --to-ports 你Emby使用的端口

**Comment by iwrt** [comment]
过滤模式设置不过滤。然后在控制管理里针对某个ip过滤。
