### ISSUE TITLE
feedback error

### ISSUE THREAD

**Issue by jkle112** [iwrt/luci-app-ikoolproxy#80]
安装的旧版本，全部文件替换升级的，运行正常，只是有三个不存在的规则文件名加载错误，没有用非官方的规则。
路由器Gl-inet MV1000W
请问哪里出错了，该如何修复！
Mon Dec 13 19:38:15 2021 daemon.info koolproxy[4024]: koolproxy v3.8.5
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: listen port=3000
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: log level=4
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: thread count=4
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: work path=/
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: program path=/usr/share/koolproxy/koolproxy
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: data path=/usr/share/koolproxy/data
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: ttl mode=160
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: ttl port=0
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: mark mode=1
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: max fd=131070
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: init adblock engine
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: load normal rule: /usr/share/koolproxy/data/rules/koolproxy.txt
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: load normal rule: /usr/share/koolproxy/data/rules/daily.txt
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: load secret rule: /usr/share/koolproxy/data/rules/kp.dat
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: load normal rule: /usr/share/koolproxy/data/rules/user.txt
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: load normal rule: /usr/share/koolproxy/data/rules/yhosts.txt
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: load normal rule: /usr/share/koolproxy/data/rules/easylistchina.txt
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: WARN: load rule failed: /usr/share/koolproxy/data/rules/easylistchina.txt
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: load normal rule: /usr/share/koolproxy/data/rules/fanboy.txt
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: WARN: load rule failed: /usr/share/koolproxy/data/rules/fanboy.txt
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: load normal rule: /usr/share/koolproxy/data/rules/anti-ad.txt
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: WARN: load rule failed: /usr/share/koolproxy/data/rules/anti-ad.txt
Mon Dec 13 19:38:20 2021 daemon.info koolproxy[4024]: load normal rule: /usr/share/koolproxy/data/rules/mv.txt

**Comment by iwrt** [comment]
删除安装新版

**Comment by jkle112** [comment]
重新编译最新版本后安装，结果问题一样的。
默认规则，都是官方的，结果也有错误信息。
ue Dec 14 20:23:08 2021 daemon.info koolproxy[28143]: koolproxy v3.8.5
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: listen port=3000
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: log level=4
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: thread count=4
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: work path=/
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: program path=/usr/share/koolproxy/koolproxy
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: data path=/usr/share/koolproxy/data
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: ttl mode=160
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: ttl port=0
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: mark mode=1
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: max fd=131070
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: init adblock engine
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: load normal rule: /usr/share/koolproxy/data/rules/koolproxy.txt
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: WARN: load rule failed: /usr/share/koolproxy/data/rules/koolproxy.txt
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: load normal rule: /usr/share/koolproxy/data/rules/daily.txt
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: WARN: load rule failed: /usr/share/koolproxy/data/rules/daily.txt
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: load secret rule: /usr/share/koolproxy/data/rules/kp.dat
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: WARN: load rule failed: /usr/share/koolproxy/data/rules/kp.dat
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: load normal rule: /usr/share/koolproxy/data/rules/user.txt
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: load normal rule: /usr/share/koolproxy/data/rules/yhosts.txt
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: WARN: load rule failed: /usr/share/koolproxy/data/rules/yhosts.txt
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: load normal rule: /usr/share/koolproxy/data/rules/adg.txt
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: WARN: load rule failed: /usr/share/koolproxy/data/rules/adg.txt
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: load normal rule: /usr/share/koolproxy/data/rules/steven.txt
Tue Dec 14 20:23:09 2021 daemon.info koolproxy[28143]: WARN: load rule failed: /usr/share/koolproxy/data/rules/steven.txt
Tue Dec 14 20:26:53 2021 cron.info crond[32444]: crond (busybox 1.30.1) started, log level 5
Tue Dec 14 20:30:00 2021 authpriv.info dropbear[3808]: Child connection from 192.168.8.179:49152
Tue Dec 14 20:30:08 2021 authpriv.notice dropbear[3808]: Password auth succeeded for 'root' from 192.168.8.179:49152
Tue Dec 14 20:30:11 2021 authpriv.info dropbear[3808]: Exit (root): Disconnect received
Tue Dec 14 20:30:44 2021 authpriv.notice beardropper[5820]: loadState() loaded 0 entries
Tue Dec 14 20:30:44 2021 authpriv.notice beardropper[5820]: loadState() loaded 0 entries
Tue Dec 14 20:30:44 2021 authpriv.notice beardropper[5820]: Running in follow mode
Tue Dec 14 20:30:46 2021 daemon.info dnsmasq[19189]: exiting on receipt of SIGTERM
Tue Dec 14 20:30:46 2021 authpriv.notice beardropper[5820]: loadState() loaded 0 entries
Tue Dec 14 20:30:46 2021 user.notice dnsmasq: DNS rebinding protection is active, will discard upstream RFC1918 responses!
Tue Dec 14 20:30:46 2021 user.notice dnsmasq: Allowing 127.0.0.0/8 responses
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: started, version 2.80 cachesize 150
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: DNS service limited to local subnets
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth nettlehash DNSSEC no-ID loop-detect inotify dumpfile
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq-dhcp[6363]: DHCP, IP range 192.168.8.100 -- 192.168.8.249, lease time 12h
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: using local addresses only for domain test
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: using local addresses only for domain onion
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: using local addresses only for domain localhost
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: using local addresses only for domain local
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: using local addresses only for domain invalid
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: using local addresses only for domain bind
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: using nameserver ::1#3535 for domain p2p
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: using nameserver 127.0.0.1#6053
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: using local addresses only for domain lan
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: read /etc/hosts - 4 addresses
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq[6363]: read /tmp/hosts/dhcp.cfg01411c - 2 addresses
Tue Dec 14 20:30:47 2021 daemon.info dnsmasq-dhcp[6363]: read /etc/ethers - 0 addresses
Tue Dec 14 20:34:18 2021 user.notice root: koolproxy restart service.
Tue Dec 14 20:34:18 2021 user.notice root: koolproxy has stopped.
Tue Dec 14 20:34:27 2021 user.notice root: koolproxy has started.
Tue Dec 14 20:34:27 2021 daemon.info koolproxy[11172]: koolproxy v3.8.5
Tue Dec 14 20:35:01 2021 daemon.err koolproxy[11172]: rule line=31275 not support ','
Tue Dec 14 20:35:01 2021 daemon.err koolproxy[11172]: rule line=31346 not support ','
Tue Dec 14 20:35:01 2021 daemon.err koolproxy[11172]: rule line=31346 not support ','
Tue Dec 14 20:35:01 2021 daemon.err koolproxy[11172]: rule line=32216 not support ','
Tue Dec 14 20:35:02 2021 daemon.err koolproxy[11172]: rule line=39157 not support ','
Tue Dec 14 20:35:02 2021 daemon.err koolproxy[11172]: rule line=39228 not support ','
Tue Dec 14 20:35:02 2021 daemon.err koolproxy[11172]: rule line=39228 not support ','
Tue Dec 14 20:35:02 2021 daemon.err koolproxy[11172]: rule line=40098 not support ','

**Comment by jkle112** [comment]
重启路由器后，导入规则正常了，但是都是默认规则，自己没有添加，还是弹出错误信息了，请看看！
Tue Dec 14 21:10:07 2021 user.notice root: koolproxy has started.
Tue Dec 14 21:10:07 2021 daemon.info koolproxy[8993]: koolproxy v3.8.5
Tue Dec 14 21:22:23 2021 daemon.info kadnode[4790]: PEERFILE: Imported 8 static peers.
Tue Dec 14 21:22:54 2021 daemon.err koolproxy[8993]: rule line=31275 not support ','
Tue Dec 14 21:22:54 2021 daemon.err koolproxy[8993]: rule line=31346 not support ','
Tue Dec 14 21:22:54 2021 daemon.err koolproxy[8993]: rule line=31346 not support ','
Tue Dec 14 21:22:54 2021 daemon.err koolproxy[8993]: rule line=32216 not support ','
Tue Dec 14 21:22:54 2021 daemon.err koolproxy[8993]: rule line=39157 not support ','
Tue Dec 14 21:22:54 2021 daemon.err koolproxy[8993]: rule line=39228 not support ','
Tue Dec 14 21:22:54 2021 daemon.err koolproxy[8993]: rule line=39228 not support ','
Tue Dec 14 21:22:54 2021 daemon.err koolproxy[8993]: rule line=40098 not support ','

**Comment by iwrt** [comment]
我这里没有出现你的错误。不知道你如何操作的。实在不行去下个编译好de固件

**Comment by jkle112** [comment]
编译好的是x64的，我的路由器型号Gl-inet MV1000W，CPU架构armv8。
