### ISSUE TITLE
系统日志，规则报错

### ISSUE THREAD

**Issue by alexliu269** [iwrt/luci-app-ikoolproxy#83]
Wed Dec 22 11:11:02 2021 daemon.err koolproxy[7971]: rule line=31275 not support ','
Wed Dec 22 11:11:02 2021 daemon.err koolproxy[7971]: rule line=31346 not support ','
Wed Dec 22 11:11:02 2021 daemon.err koolproxy[7971]: rule line=31346 not support ','
Wed Dec 22 11:11:02 2021 daemon.err koolproxy[7971]: rule line=32216 not support ','
Wed Dec 22 11:11:02 2021 daemon.err koolproxy[7971]: rule line=39157 not support ','
Wed Dec 22 11:11:02 2021 daemon.err koolproxy[7971]: rule line=39228 not support ','
Wed Dec 22 11:11:02 2021 daemon.err koolproxy[7971]: rule line=39228 not support ','
Wed Dec 22 11:11:02 2021 daemon.err koolproxy[7971]: rule line=40098 not support ','
Wed Dec 22 11:11:18 2021 daemon.info procd: Instance haproxy::instance1 s in a crash loop 6 crashes, 0 seconds since last crash

**Comment by iwrt** [comment]
x86下没有问题哦，不知道你是什么坂本

**Comment by alexliu269** [comment]
x86 全新编译进来的。

**Comment by zkevinzh** [comment]
同x86，有相同类似现象
Wed Feb  9 03:00:20 2022 daemon.err koolproxy[24718]: rule line=31368 not support ','
Wed Feb  9 03:00:20 2022 daemon.err koolproxy[24718]: rule line=31439 not support ','
Wed Feb  9 03:00:20 2022 daemon.err koolproxy[24718]: rule line=31439 not support ','
Wed Feb  9 03:00:20 2022 daemon.err koolproxy[24718]: rule line=32309 not support ','
Wed Feb  9 03:00:20 2022 daemon.err koolproxy[24718]: rule line=39254 not support ','
Wed Feb  9 03:00:20 2022 daemon.err koolproxy[24718]: rule line=39325 not support ','
Wed Feb  9 03:00:20 2022 daemon.err koolproxy[24718]: rule line=39325 not support ','
Wed Feb  9 03:00:20 2022 daemon.err koolproxy[24718]: rule line=40195 not support ','

经过一番摸索，发现是这个规则文件问题：/usr/share/koolproxy/data/rules/adgk.txt

31368 ||https://dilidili.wang,~h5.dilidili.wang##a[href*=".11h5."] img
31439 ||https://iqiyi.com,~mall.iqiyi.com,~so.iqiyi.com##a[href*="http://mall.iqiyi.com/item/"]
32309 ||https://ifeng.com,~imall.ifeng.com##a[href*="imall.ifeng."]
39254 ||http://dilidili.wang,~h5.dilidili.wang##a[href*=".11h5."] img
39325 ||http://iqiyi.com,~mall.iqiyi.com,~so.iqiyi.com##a[href*="http://mall.iqiyi.com/item/"]
40195 ||http://ifeng.com,~imall.ifeng.com##a[href*="imall.ifeng."]

观察这几条规则看出来"，"号后面都接了个"~"，尝试把"~"删了之后就不会报错了。
我不太懂规则的编写，这个"~"是feature还是bug？能去掉吗？
