### ISSUE TITLE
我也不知道我哪里错了就是无法启动

### ISSUE THREAD

**Issue by brianzc0306** [iwrt/luci-app-ikoolproxy#86]
系统日志
Wed Dec 29 11:47:26 2021 kern.info kernel: [  426.066903] koolproxy[8511]: segfault at 7fd8a37a8900 ip 00007fd8a37a8900 sp 00007fd8a37a8898 error 15
Wed Dec 29 11:47:26 2021 kern.info kernel: [  426.067182] Code: 00 00 95 34 41 00 00 00 00 00 d8 d2 40 a2 d8 7f 00 00 41 bb 30 2f 41 00 49 ba e0 88 7a a3 d8 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 88 7a a3 d8 7f 00 00 49 ff e3 90 d8 7f
Wed Dec 29 11:47:28 2021 user.notice root: koolproxy reload service.

![image](https://user-images.githubusercontent.com/48046657/147625931-a7a60cb8-fbd0-44a2-bcc0-bf95b7bd77af.png)

**Comment by brianzc0306** [comment]
> 系统日志 Wed Dec 29 11:47:26 2021 kern.info kernel: [ 426.066903] koolproxy[8511]: segfault at 7fd8a37a8900 ip 00007fd8a37a8900 sp 00007fd8a37a8898 error 15 Wed Dec 29 11:47:26 2021 kern.info kernel: [ 426.067182] Code: 00 00 95 34 41 00 00 00 00 00 d8 d2 40 a2 d8 7f 00 00 41 bb 30 2f 41 00 49 ba e0 88 7a a3 d8 7f 00 00 49 ff e3 90 00 00 00 00 <41> bb 50 2e 41 00 49 ba e0 88 7a a3 d8 7f 00 00 49 ff e3 90 d8 7f Wed Dec 29 11:47:28 2021 user.notice root: koolproxy reload service.
> 
> ![image](https://user-images.githubusercontent.com/48046657/147625931-a7a60cb8-fbd0-44a2-bcc0-bf95b7bd77af.png)

原因找到了 不兼容5.10的内核

**Comment by saoba1982** [comment]
我也是一样.希望大神可以修复一下内核支持5.10

**Comment by ssdsl0126** [comment]
别使用5.10内核就行了

**Comment by alexliu269** [comment]
目前5.4可以启动，5.10 5.15都无法启动。如果要使用这个，在大佬没有修复前只能用5.4内核的。
