### ISSUE TITLE
houzi-发布了koolproxy 3.8.7 ikoolproxy可以更换吗

### ISSUE THREAD

**Issue by Karmylr** [iwrt/luci-app-ikoolproxy#89]
如题

**Comment by iwrt** [comment]
没有见到啊。你有包吗，传一份

**Comment by Karmylr** [comment]
> 没有见到啊。你有包吗，传一份

https://t.me/c/1068317617/186315

**Comment by iwrt** [comment]
组名发一些，我进不去

**Comment by uminoai** [comment]
> 组名发一些，我进不去
[koolproxy_3.8.7_20220103_X86_64.tar.gz](https://github.com/iwrt/luci-app-ikoolproxy/files/7801652/koolproxy_3.8.7_20220103_X86_64.tar.gz)
