### ISSUE TITLE
ikoolproxy开启后110.110.110.110证书无法下载，运行中经常变成未运行

### ISSUE THREAD

**Issue by pengpeng21** [iwrt/luci-app-ikoolproxy#94]
内核版本：5.10.88
ikoolproxy版本：3.8.6

ikoolproxy开启后110.110.110.110证书无法下载
手动下载安装证书，运行ikoolproxy，配置mac地址过滤，网页无法访问
插件不稳定经常停止运行

**Comment by zhengyiquan** [comment]
不支持5.10的内核版本啊

**Comment by smartymoon** [comment]
原来如此

**Comment by BiuZero** [comment]
原来如此🤦‍♂️
